### ISSUE TITLE
Mixed content

### ISSUE THREAD

**Issue by jlelse** [Sommerregen/grav-theme-developer#6]
Somehow my browser shows me, that some font's are loaded via HTTP instead of HTTPS. The root of the problem is in some JS files.

**Comment by Sommerregen** [comment]
@jlelse you are right. Changing all occurrences of either `http://` or `https://` [default.html.twig#L29-L49](https://github.com/Sommerregen/grav-theme-developer/blob/develop/templates/default.html.twig#L29-L49) to a relative URL without a scheme `//`should solve this issue.

**Comment by jlelse** [comment]
Or https, because I think there's only a warning when the page is loaded via https but some dependencies via http.

**Comment by Sommerregen** [comment]
@jlelse I changed all occurrences. The mixed content warnings should be gone now.

**Comment by jlelse** [comment]
Great!
