### ISSUE TITLE
Github Activity URL 404

### ISSUE THREAD

**Issue by tschechniker** [Sommerregen/grav-theme-developer#7]
Hi,

the Github Activity CSS an JS points to a non existing site:

http://caseyscarborough.com/github-activity/github-activity-0.1.0.min.css --> 404
http://caseyscarborough.com/github-activity/github-activity-0.1.0.min.js --> 404

Maybe they should be included in your Theme?

**Comment by Sommerregen** [comment]
Good point 👍 . Will add those assets as well as the octoicons css to the theme.

**Comment by Sommerregen** [comment]
@tschechniker I included the Github Activity CSS an JS as well as Octicons and Mustache in the theme.
